import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>SpaceX API Displayer by Elyas Al-Amri</title>
        <meta name="description" content="Generated by create next app"/>
      </Head>
      <p>This website is an implementation that uses GraphQL to fetch data from SpaceX API and displays the results</p>
    </>
  )
}

export default Home
