import type {NextPage} from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Home: NextPage = () => (
    <>
      <Head>
        <title>SpaceX API Displayer by Elyas Al-Amri</title>
        <meta name="description" content="Generated by create next app"/>
      </Head>
      <p className="text-center">
        This website is an implementation that uses GraphQL to fetch data from SpaceX API and displays the results.
      </p>
      <Link href="/launches">
        <a className="mt-4 block mx-auto px-20 py-10 text-3xl font-bold border-2 bg-white dark:bg-orange-500
         shadow-md rounded">
          Open Launches
        </a>
      </Link>
    </>
)

export default Home
